# Generated by Django 5.1.6 on 2025-03-08 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_order_payment_status_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_status',
        ),
    ]
